- name: Copy catalogue service file
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service


- name: systemctl deamon reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: start and enable {{ component }}
  ansible.builtin.service:
    name: "{{ component }}"
    state: restarted
    enabled: yes